- hosts: slurm-controller
  become: yes
  roles:
    - initalize-vm
    - add-to-dhcp
    - add-to-dns
    - provision-vm
    - harden-os
    - realm-join
    - copy-ssh-keys
    - configure-chrony
    - provision-filebeat
    - provision-node-exporter
    - configure-slurm
    - provision-mta
    - provision-slurm-node-exporter
    - provision-ib-node-exporter
    - provision-lusterfs-node-exporter
